import { createCn } from 'cn/config'

export const cn = createCn({
  extend: {
    classGroups: {
      'font-size': [
        {
          text: [
            'hero-mobile',
            'hero-mobile--line-height',
            'intro-heading-mobile',
            'intro-heading-mobile--line-height',
            'display-mobile',
            'display-mobile--line-height',
            'section-mobile',
            'section-mobile--line-height',
            'service-mobile',
            'service-mobile--line-height',
            'results-heading-mobile',
            'results-heading-mobile--line-height',
            'results-stat-mobile',
            'results-stat-mobile--line-height',
            'results-description-mobile',
            'results-description-mobile--line-height',
            'stat-mobile',
            'stat-mobile--line-height',
            'quote-mobile',
            'quote-mobile--line-height',
            'hero',
            'hero--line-height',
            'hero--letter-spacing',
            'display',
            'display--line-height',
            'display--letter-spacing',
            'section',
            'section--line-height',
            'section--letter-spacing',
            'service',
            'service--line-height',
            'service--letter-spacing',
            'stat',
            'stat--line-height',
            'quote',
            'quote--line-height',
            'quote--letter-spacing',
            'intro',
            'intro--line-height',
            'project',
            'project--line-height',
            'project--letter-spacing',
            'body',
            'body--line-height',
            'small',
            'eyebrow',
            'eyebrow--line-height',
            'caption',
          ],
        },
      ],
    },
  },
})
